# Generated by Django 3.1 on 2020-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20201116_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_phone',
            field=models.CharField(max_length=10),
        ),
    ]
