# Generated by Django 3.1 on 2020-11-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20201116_1942'),
        ('tables', '0003_auto_20201116_1632'),
    ]

    operations = [
    ]
