# Generated by Django 3.1 on 2020-11-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20201118_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_mname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
