# Generated by Django 3.1 on 2020-11-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20201118_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='voter_status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], null=True),
        ),
    ]
