# Generated by Django 3.1 on 2020-11-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20201118_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_loc',
            field=models.ImageField(upload_to='symbols/'),
        ),
    ]
