# Generated by Django 3.1 on 2020-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20201121_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_mob',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
