# Generated by Django 3.1 on 2020-11-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20201121_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='support_status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='support_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.student'),
        ),
    ]
