# Generated by Django 3.1 on 2020-11-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_auto_20201126_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='elect_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_temp_mob',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
