# Generated by Django 3.1 on 2020-11-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_auto_20201128_1113'),
    ]

    operations = [
    ]
