# Generated by Django 3.1 on 2020-11-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_remove_student_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cand_support_id1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='support1', to='tables.student'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cand_support_id2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='support2', to='tables.student'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.party'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.symbol'),
        ),
    ]
