# Generated by Django 3.1 on 2020-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_auto_20201130_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='accept_sts',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
