# Generated by Django 3.1 on 2020-12-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_candidate_accept_sts'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_email',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
