# Generated by Django 3.1 on 2020-12-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_candidate_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='panel_votes',
            field=models.IntegerField(default=1),
        ),
    ]
