# Generated by Django 3.1 on 2020-12-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_panel_panel_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='secureVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initState', models.IntegerField(default=0)),
                ('remainingOtp', models.IntegerField(default=2)),
                ('completed', models.IntegerField(default=0)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.student')),
            ],
        ),
    ]
