# Generated by Django 3.1 on 2020-12-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_securevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='securevote',
            name='otp',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
