# Generated by Django 3.1 on 2020-12-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_securevote_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='panel_status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1),
        ),
        migrations.AlterField(
            model_name='securevote',
            name='completed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securevote',
            name='initState',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='securevote',
            name='otp',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
