# Generated by Django 3.1.7 on 2023-02-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_auto_20201212_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securevote',
            name='remainingOtp',
            field=models.IntegerField(default=3),
        ),
    ]
