# Generated by Django 3.1.7 on 2023-03-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0024_auto_20230222_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admno', models.CharField(default=None, max_length=20, null=True)),
                ('fname', models.CharField(default=None, max_length=20, null=True)),
                ('lname', models.CharField(default=None, max_length=20, null=True)),
                ('gender', models.CharField(default=None, max_length=20, null=True)),
                ('batch', models.CharField(default=None, max_length=20, null=True)),
                ('email', models.CharField(default=None, max_length=20, null=True)),
                ('sem', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
    ]
