# Generated by Django 3.1.7 on 2023-03-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0025_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='stud',
        ),
    ]
