# Generated by Django 3.1.7 on 2023-03-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0027_auto_20230307_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='stud_mname',
        ),
    ]
