# Generated by Django 3.1.7 on 2023-03-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0028_remove_stud_stud_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='stud_email',
            field=models.CharField(default=None, max_length=70, null=True),
        ),
    ]
