# Generated by Django 4.1.7 on 2023-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0029_auto_20230307_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
