# Generated by Django 4.1.7 on 2023-03-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0030_alter_student_stud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_dob',
            field=models.DateField(default='0000-00-00', null=True),
        ),
    ]
