# Generated by Django 4.1.7 on 2023-03-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0031_alter_student_stud_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_dob',
            field=models.DateField(null=True),
        ),
    ]
